version: '3.1'

services:
  app:
    image: wordpress:fpm-alpine
    deploy:
      replicas: 3
    environment:
      - "WORDPRESS_DB_HOST=mariadb:3306"
      - "WORDPRESS_DB_USER=wordpress"
      - "WORDPRESS_DB_PASSWORD=wordpress"
    ports:
      - 80
    networks:
      - wordpress-network

  mariadb:
    image: mariadb
    deploy:
      replicas: 1
    environment:
      - "MYSQL_ROOT_PASSWORD=wordpress"
      - "MYSQL_DATABASE=wordpress"
      - "MYSQL_USER=wordpress"
      - "MYSQL_PASSWORD=wordpress"
    networks:
      - wordpress-network
    volumes:
     - db:/data/db

volumes:
  db:
    driver: local

networks:
  wordpress-network:
    driver: overlay
