version: '2'

services:
  app:
    image: wordpress
    environment:
      - "WORDPRESS_DB_HOST=db:3306"
      - "WORDPRESS_DB_PASSWORD=wordpress"
      - "constraint:nodeType==app"
    ports:
      - 80
    links:
      - db:mysql
    networks:
      - my-network
    restart: always

  db:
    restart: always
    image: mariadb
    environment:
      - "MYSQL_ROOT_PASSWORD=wordpress"
      - "MYSQL_DATABASE=wordpress"
      - "MYSQL_USER=wordpress"
      - "MYSQL_PASSWORD=wordpress"
      - "constraint:nodeType==app"
    networks:
      - my-network
    volumes:
     - db:/data/db

volumes:
  db:
    driver: local

networks:
  my-network:
    driver: overlay
