version: '3.1'

services:
  app:
    image: dtr.david.dtcntr.net/engineering/wordpress
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      labels:
        com.docker.ucp.mesh.http: "external_route=http://wordpress.local,internal_port=80"
    environment:
      - "WORDPRESS_DB_HOST=mariadb:3306"
      - "WORDPRESS_DB_USER=wordpress"
      - "WORDPRESS_DB_PASSWORD=wordpress"
    ports:
      - 80
    networks:
      - wordpress-network
      - ucp-hrm

  mariadb:
    image: dtr.david.dtcntr.net/engineering/mariadb
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    environment:
      - "MYSQL_ROOT_PASSWORD=wordpress"
      - "MYSQL_DATABASE=wordpress"
      - "MYSQL_USER=wordpress"
      - "MYSQL_PASSWORD=wordpress"
      - "constraint:nodeType==app"
    networks:
      - wordpress-network
    volumes:
     - db:/data/db

volumes:
  db:
    driver: local

networks:
  wordpress-network:
    driver: overlay
  ucp-hrm:
    external: true
