version: '3.1'

services:
  app:
    image: wordpress
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.labels.type == app
      labels:
        com.docker.ucp.mesh.http: "external_route=http://wordpress.local,internal_port=80"
    environment:
      WORDPRESS_DB_HOST: 'mariadb:3306'
      WORDPRESS_DB_PASSWORD: '/run/secrets/WORDPRESS_DB_PASSWORD'
    secrets:
      - source: MYSQL_PASSWORD
        target: WORDPRESS_DB_PASSWORD
        uid: "0"
        gid: "0"
        mode: 0400
    ports:
      - 80
    networks:
      - wordpress-network
      - ucp-hrm

  mariadb:
    image: mariadb
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == app
    environment:
      MYSQL_ROOT_PASSWORD: '/run/secrets/MYSQL_ROOT_PASSWORD'
      MYSQL_DATABASE: '/run/secrets/MYSQL_DATABASE'
      MYSQL_USER: '/run/secrets/MYSQL_USER'
      MYSQL_PASSWORD: '/run/secrets/MYSQL_PASSWORD'
    secrets:
      - source: MYSQL_PASSWORD
        target: MYSQL_PASSWORD
        uid: "0"
        gid: "0"
        mode: 0400
      - source: MYSQL_USER
        target: MYSQL_USER
        uid: "0"
        gid: "0"
        mode: 0400
      - source: MYSQL_DATABASE
        target: MYSQL_DATABASE
        uid: "0"
        gid: "0"
        mode: 0400
      - source: MYSQL_ROOT_PASSWORD
        target: MYSQL_ROOT_PASSWORD
        uid: "0"
        gid: "0"
        mode: 0400
    networks:
      - wordpress-network
    volumes:
     - db:/data/db

volumes:
  db:
    driver: local

networks:
  wordpress-network:
    driver: overlay
  ucp-hrm:
    external: true

secrets:
  MYSQL_PASSWORD:
    external: true
  MYSQL_USER:
    external: true
  MYSQL_DATABASE:
    external: true
  MYSQL_ROOT_PASSWORD:
    external: true
