version: '3.1'

services:
  app:
    image: wordpress
    deploy:
      replicas: 3
      labels:
        com.docker.ucp.mesh.http: "external_route=http://$WORDPRESS_DOMAIN,internal_port=80"
    environment:
      WORDPRESS_DB_HOST: 'mariadb:3306'
      WORDPRESS_DB_PASSWORD: '/run/secrets/MYSQL_ROOT_PASSWORD'
    secrets:
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - 80
    networks:
      - wordpress-network
      - ucp-hrm

  mariadb:
    image: mariadb
    deploy:
      replicas: 1
    environment:
      MYSQL_ROOT_PASSWORD: '/run/secrets/MYSQL_ROOT_PASSWORD'
      MYSQL_DATABASE: '/run/secrets/MYSQL_DATABASE'
      MYSQL_USER: '/run/secrets/MYSQL_USER'
      MYSQL_PASSWORD: '/run/secrets/MYSQL_PASSWORD'
    secrets:
      - MYSQL_PASSWORD
      - MYSQL_USER
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
    networks:
      - wordpress-network
    volumes:
     - db:/data/db

volumes:
  db:
    driver: local

networks:
  wordpress-network:
    driver: overlay
  ucp-hrm:
    external: true

secrets:
  MYSQL_PASSWORD:
    external: true
  MYSQL_USER:
    external: true
  MYSQL_DATABASE:
    external: true
  MYSQL_ROOT_PASSWORD:
    external: true
